[project]
name = "fordefi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.6",
    "ecdsa>=0.19.0",
    "typer>=0.15.1",
    "requests==2.31.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.setuptools.package-data]
"fordefi" = ["py.typed"]


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "C90" ]


[tool.mypy]
follow_imports = "silent"
strict = true
disallow_untyped_defs = true
disable_error_code = "import-untyped"
ignore_missing_imports = false
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = false

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.394",
    "pytest>=8.3.4",
    "httpretty>=1.1.4",
    "pytest-httpserver>=1.1.1",
    "pytest-cov>=6.0.0",
    "pytest-recording==0.13.2",
    "uv>=0.5.31",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
