#!/usr/bin/env bash
OPENAPI_SPEC="openapi.yaml"
OUTPUT="evmtransfers.py"
curl https://docs.fordefi.com/_spec/api/openapi.yaml?download -o $OPENAPI_SPEC
python extract_component_schema.py CreateEvmTransferRequest $OPENAPI_SPEC
datamodel-codegen --input CreateEvmTransferRequest.yaml \
                  --input-file-type=openapi \
                  --target-python-version=3.13 \
                  --output-model-type=pydantic_v2.BaseModel \
                  --use-annotated \
                  --output $OUTPUT

sed -i "s/#   filename: /#/" $OUTPUT
sed -i "s/# generated by datamodel-codegen:/# generated by datamodel-codegen:\n# ruff: noqa: E501/" $OUTPUT

ruff check --fix --unsafe-fixes $OUTPUT
ruff format $OUTPUT
