name: Run unit tests

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/unit-tests.yml
      - "**.py"

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/unit-tests.yml
      - "**.py"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: python -m pip install uv

      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/uv.lock') }}

      - name: Install dependencies
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
        run: uv sync

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
